### PR TITLE
Make onError totally configurable by user config

### LINKED ISSUE #14: Fail gracefully, if connection to seq fails
Hi!

We use `pino-seq` together with `pino` in our Next.js app to log errors to Seq. Today, an error occurred in our Seq server, which made the connection between our app and Seq fail with the following error:

```
2020-11-19T07:41:47.743700409Z events.js:306 2020-11-19T07:41:47.743785314Z throw err;
// Unhandled 'error' event 2020-11-19T07:41:47.743803315Z ^ 2020-11-19T07:41:47.743807616Z
2020-11-19T07:41:47.743811616Z Error [ERR_UNHANDLED_ERROR]: Unhandled error.
('HTTP log shipping failed: 502') 2020-11-19T07:41:47.743815916Z at PinoSeqStream.emit (events.js:304:17)
2020-11-19T07:41:47.743819816Z at emitErrorNT (internal/streams/destroy.js:92:8) 
2020-11-19T07:41:47.743823717Z at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) 
2020-11-19T07:41:47.743827917Z at processTicksAndRejections (internal/process/task_queues.js:84:21) 
{
 2020-11-19T07:41:47.743831817Z code: 'ERR_UNHANDLED_ERROR',
2020-11-19T07:41:47.743835517Z context: 'HTTP log shipping failed: 502' 2020-11-19T07:41:47.743839318Z } 2020-11-19T07:41:47.763250218Z error Command failed with exit code 1.
2020-11-19T07:41:47.763348224Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This crashed our whole Next.js app.

After some digging, I see that the `onError` method will always call `this.destroy`, implemented here:
https://github.com/datalust/pino-seq/blob/8971831caa468ff4ead5ff75cfcd36de1ebfdb7b/pinoSeqStream.js#L22

So users cannot remove this. I was wondering if it was a deliberate choice, and if so, what is the explanation? Would it be possible to make the `onError` totally overrideable such that connection errors to `Seq` will not crash our entire app?

My current solution was to override the destroy method of the stream like so:

```js
  const stream = pinoToSeq.createStream({
    apiKey: process.env.SEQ_API_KEY,
    serverUrl: process.env.SEQ_SERVER_URL,
  })

  /**
   * HACK: https://nodejs.org/api/stream.html#stream_writable_destroy_error
   * should not be overriden, but pino-seq wants to destroy if connection to seq fails.
   */
  stream.destroy = console.error

```

but the [Node.js docs](https://nodejs.org/api/stream.html#stream_writable_destroy_error) tells me I should not do that.

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixes #14

### CODE REVIEW

**Comment by larenelg** [comment]
Hi @balazsorban44 - thanks so much for this change request!

I've just tested locally with a quick Express app that I spun up - [express-pino-seq](https://github.com/datalust/express-pino-seq) - and running `npm install ../pino-seq` (a local folder of pino-seq with the changes from this PR)

I seem to get this error when I browse [localhost:3000](localhost:3000) when no Seq server is running? Any clues to what this might be? I'm digging in as well.

```
> express-pino-seq@0.0.1 start
> node ./bin/www | pino-seq

node:internal/streams/writable:841
    state.bufferedIndex < state.buffered.length ||
          ^

TypeError: Cannot read property 'bufferedIndex' of undefined
    at SeqLogger.Writable.destroy [as _onError] (node:internal/streams/writable:841:11)
    at /Users/larenelg/Dev/Datalust/pino-seq/node_modules/seq-logging/seq_logger.js:186:22
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by balazsorban44** [comment]
I can't even get that far with `express-pio-seq`:

```
node ./bin/www | pino-seq
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/balazs/projects/express-pino-seq/bin/www'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```


Going into `node_modules/pino-seq/pinoSeqStream.js` in my app, and changing the line as in this PR though produces the wished result, and instead of crashing my app, it will start logging the error to the console.

**Comment by larenelg** [comment]
Oh I see - that might be because of different versions of Node. May I please ask what version you are running?

**Comment by larenelg** [comment]
Hi @balazsorban44 - thanks for your patience on this issue. I'm a relatively new maintainer for this repo so still getting up to speed.

After some thinking, there's no reason for us to be using `destroy()` when there is an error, but I'll make those changes after merging yours, and do a new release.

Thanks for your work on this!!

**Pull request merged**
